sudo: required

language: node_js
node_js:
  - '14'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

services:
  - docker

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com  

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless
  - docker build -t azizmavlyanov/angular-front:v1 --build-arg API_URL=$API_URL -f Dockerfile .
  - docker tag azizmavlyanov/angular-front:v1 registry.heroku.com/$HEROKU_APP/web 

deploy:   
  provider: script
  script: 
          docker push azizmavlyanov/angular-front:v1;
          docker push registry.heroku.com/$HEROKU_APP/web;
          heroku container:release web --app $HEROKU_APP
  on:
    branch: master
